// Generated by scripts/sync-oss.mjs from thetahealth/mirobody 1.5.4 (faffe06ebf9ffe0ab00e046ec5ab9a8634cc0f06).
// Do not edit: run `npm run oss:sync`. Mintlify snippets cannot import one another
// and a page receives only the exports it imports, so every export below is
// self-contained and carries the facts it reads.

export const facts = {
  "version": "1.5.4",
  "commit": "faffe06ebf9ffe0ab00e046ec5ab9a8634cc0f06",
  "commitShort": "faffe06",
  "repo": "https://github.com/thetahealth/mirobody",
  "python": "3.12",
  "port": 18060,
  "url": "http://localhost:18060",
  "pgPort": 18062,
  "redisPort": null,
  "account": "you@mirobody.ai",
  "accounts": [
    "you@mirobody.ai",
    "mom@mirobody.ai"
  ],
  "code": "111111",
  "mcpUrlTtlDays": 10,
  "llmKeys": [
    "OPENROUTER_API_KEY",
    "DASHSCOPE_API_KEY",
    "GOOGLE_API_KEY",
    "OPENAI_API_KEY",
    "ANTHROPIC_API_KEY",
    "DEEPSEEK_API_KEY"
  ],
  "cli": [
    "serve",
    "dev",
    "worker",
    "doctor",
    "fetch",
    "parse",
    "import",
    "resolve",
    "device-bundle",
    "mcp",
    "migrate-observations",
    "migrate-genotypes",
    "recode"
  ],
  "tools": {
    "mcp": [
      "query_genetic_data",
      "query_health_indicators",
      "query_medications",
      "query_pharmacogenomics",
      "resolve_indicator",
      "convert_unit",
      "normalize_unit"
    ],
    "gated": [
      "query_genetic_data",
      "query_pharmacogenomics",
      "query_health_indicators",
      "query_medications"
    ]
  },
  "readme": {
    "en": {
      "tagline": "Turn scattered health data into answers you can trace.",
      "stages": [
        {
          "mark": "①",
          "name": "Collect",
          "what": "Files, devices and journal entries come in; the source is kept, so every reading points back to it."
        },
        {
          "mark": "②",
          "name": "Translate",
          "what": "`A1c`, `HbA1c` and `Glycated Hemoglobin` resolve to one code, units to one standard, offline. A name it cannot place stays unresolved."
        },
        {
          "mark": "③",
          "name": "Agent",
          "what": "Ask over the coded record: trends, comparisons across labs and devices, a chart, and the file behind every number."
        }
      ]
    },
    "zh": {
      "tagline": "把分散的健康数据，变成有据可查的答案。",
      "stages": [
        {
          "mark": "①",
          "name": "收集 Collect",
          "what": "文件、设备和日记汇入系统；原始来源保留下来，每条读数都能指回它。"
        },
        {
          "mark": "②",
          "name": "转译 Translate",
          "what": "`A1c`、`HbA1c`、`糖化血红蛋白` 解析为同一个编码，单位统一到同一标准，全程离线。无法确定的名称保持未解析。"
        },
        {
          "mark": "③",
          "name": "智能体 Agent",
          "what": "在编码后的记录上提问：看趋势、跨医院和设备比较、画图，并标出每个数字来自哪份文件。"
        }
      ]
    }
  },
  "source": {
    "cli": "mirobody/cli.py",
    "tools": "mirobody/agent/tools"
  }
};

export const Fact = ({ k, code = false, sep = ", " }) => {
  const facts = {"version":"1.5.4","commit":"faffe06ebf9ffe0ab00e046ec5ab9a8634cc0f06","commitShort":"faffe06","repo":"https://github.com/thetahealth/mirobody","python":"3.12","port":18060,"url":"http://localhost:18060","pgPort":18062,"redisPort":null,"account":"you@mirobody.ai","accounts":["you@mirobody.ai","mom@mirobody.ai"],"code":"111111","mcpUrlTtlDays":10,"llmKeys":["OPENROUTER_API_KEY","DASHSCOPE_API_KEY","GOOGLE_API_KEY","OPENAI_API_KEY","ANTHROPIC_API_KEY","DEEPSEEK_API_KEY"],"cli":["serve","dev","worker","doctor","fetch","parse","import","resolve","device-bundle","mcp","migrate-observations","migrate-genotypes","recode"],"tools":{"mcp":["query_genetic_data","query_health_indicators","query_medications","query_pharmacogenomics","resolve_indicator","convert_unit","normalize_unit"],"gated":["query_genetic_data","query_pharmacogenomics","query_health_indicators","query_medications"]},"readme":{"en":{"tagline":"Turn scattered health data into answers you can trace.","stages":[{"mark":"①","name":"Collect","what":"Files, devices and journal entries come in; the source is kept, so every reading points back to it."},{"mark":"②","name":"Translate","what":"`A1c`, `HbA1c` and `Glycated Hemoglobin` resolve to one code, units to one standard, offline. A name it cannot place stays unresolved."},{"mark":"③","name":"Agent","what":"Ask over the coded record: trends, comparisons across labs and devices, a chart, and the file behind every number."}]},"zh":{"tagline":"把分散的健康数据，变成有据可查的答案。","stages":[{"mark":"①","name":"收集 Collect","what":"文件、设备和日记汇入系统；原始来源保留下来，每条读数都能指回它。"},{"mark":"②","name":"转译 Translate","what":"`A1c`、`HbA1c`、`糖化血红蛋白` 解析为同一个编码，单位统一到同一标准，全程离线。无法确定的名称保持未解析。"},{"mark":"③","name":"智能体 Agent","what":"在编码后的记录上提问：看趋势、跨医院和设备比较、画图，并标出每个数字来自哪份文件。"}]}},"source":{"cli":"mirobody/cli.py","tools":"mirobody/agent/tools"}};
  const value = k.split(".").reduce((o, p) => (o == null ? undefined : o[p]), facts);
  if (value === undefined) return <span>{"[unknown fact " + k + "]"}</span>;
  const items = Array.isArray(value) ? value : [value];
  return (
    <>
      {items.map((item, i) => (
        <span key={i}>
          {i > 0 ? sep : null}
          {code ? <code>{String(item)}</code> : String(item)}
        </span>
      ))}
    </>
  );
};

export const ossUrl = (path = "") => {
  const base = "https://github.com/thetahealth/mirobody";
  const commit = "faffe06ebf9ffe0ab00e046ec5ab9a8634cc0f06";
  if (!path) return base + "/tree/" + commit;
  return base + (path.endsWith("/") ? "/tree/" : "/blob/") + commit + "/" + path.replace(/\/$/, "");
};

export const OssLink = ({ path = "", children }) => {
  const base = "https://github.com/thetahealth/mirobody";
  const commit = "faffe06ebf9ffe0ab00e046ec5ab9a8634cc0f06";
  const href = !path ? base + "/tree/" + commit : base + (path.endsWith("/") ? "/tree/" : "/blob/") + commit + "/" + path.replace(/\/$/, "");
  return <a href={href}>{children ?? <code>{path}</code>}</a>;
};

export const OssSource = ({ path, lang = "en" }) => {
  const href = "https://github.com/thetahealth/mirobody/blob/faffe06ebf9ffe0ab00e046ec5ab9a8634cc0f06/" + path;
  return (
    <p className="text-sm text-gray-500 dark:text-gray-400">
      {lang === "zh" ? "对应 mirobody " : "For mirobody "}
      <code>1.5.4</code>
      {lang === "zh" ? " · 源文件 " : " · source "}
      <a href={href}>
        <code>{path}</code>
      </a>
    </p>
  );
};

export const OssVersion = ({ lang = "en" }) => (
  <p className="text-sm text-gray-500 dark:text-gray-400">
    {lang === "zh" ? "对应 mirobody " : "Written for mirobody "}
    <a href="https://github.com/thetahealth/mirobody/tree/faffe06ebf9ffe0ab00e046ec5ab9a8634cc0f06">
      <code>1.5.4</code>
    </a>
  </p>
);

export const Stages = ({ lang = "en" }) => {
  const readme = {"en":{"tagline":"Turn scattered health data into answers you can trace.","stages":[{"mark":"①","name":"Collect","what":"Files, devices and journal entries come in; the source is kept, so every reading points back to it."},{"mark":"②","name":"Translate","what":"`A1c`, `HbA1c` and `Glycated Hemoglobin` resolve to one code, units to one standard, offline. A name it cannot place stays unresolved."},{"mark":"③","name":"Agent","what":"Ask over the coded record: trends, comparisons across labs and devices, a chart, and the file behind every number."}]},"zh":{"tagline":"把分散的健康数据，变成有据可查的答案。","stages":[{"mark":"①","name":"收集 Collect","what":"文件、设备和日记汇入系统；原始来源保留下来，每条读数都能指回它。"},{"mark":"②","name":"转译 Translate","what":"`A1c`、`HbA1c`、`糖化血红蛋白` 解析为同一个编码，单位统一到同一标准，全程离线。无法确定的名称保持未解析。"},{"mark":"③","name":"智能体 Agent","what":"在编码后的记录上提问：看趋势、跨医院和设备比较、画图，并标出每个数字来自哪份文件。"}]}};
  const stages = (readme[lang] || readme.en).stages;
  const inline = (text) =>
    text.split("`").map((part, i) => (i % 2 ? <code key={i}>{part}</code> : <span key={i}>{part}</span>));
  return (
    <div className="grid gap-4 sm:grid-cols-3 not-prose">
      {stages.map((stage) => (
        <div key={stage.mark} className="rounded-2xl border border-gray-200 dark:border-white/10 p-5">
          <p className="font-semibold text-gray-900 dark:text-gray-100">
            {stage.mark} {stage.name}
          </p>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">{inline(stage.what)}</p>
        </div>
      ))}
    </div>
  );
};
