/**
 * Render the mirobody repository's own documentation into the Open Source pages.
 *
 *   npm run oss:sync     write en/<slug>.mdx + zh/<slug>.mdx, images/oss/, snippets/oss-facts.jsx
 *   npm run check:sync   render in memory and fail if anything committed differs
 *
 * Facts about the engine are written once, in the repository, next to the code
 * they describe. This site renders them at the commit `oss.lock` pins and never
 * edits the prose: a generated page is overwritten on every sync, and CI fails when
 * a committed copy differs from what the pinned commit renders to.
 *
 * What the conversion does, markdown → Mintlify MDX:
 * - the first `# ` heading becomes the frontmatter title; the "English · 中文"
 *   switcher line is dropped (the site has its own language switcher)
 * - every heading gets an explicit `{#id}` with GitHub's slug, so the repository's
 *   own `#anchor` links keep working unchanged
 * - `x.md` links go to the site page that file became, or to the file on GitHub at
 *   the pinned commit; docs.mirobody.ai links become site-relative
 * - images are copied under images/oss/ (replaced wholesale on every sync);
 *   `<picture>` light/dark pairs become Mintlify's light/dark image pair
 * - raw HTML is rewritten as JSX, and HTML comments are dropped
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync, copyFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { compile } from "@mdx-js/mdx";
import GithubSlugger from "github-slugger";
import { fromHtml } from "hast-util-from-html";
import { toString } from "mdast-util-to-string";
import { find, html as htmlSchema } from "property-information";
import remarkGfm from "remark-gfm";
import remarkMdx from "remark-mdx";
import remarkParse from "remark-parse";
import remarkStringify from "remark-stringify";
import { unified } from "unified";
import { visit, SKIP } from "unist-util-visit";
import { readFacts } from "./lib/facts.mjs";
import {
  LOCALES, ROOT, VENDOR, assertVendor, githubUrl, pageIndex, readMap, readVendor, resolveRepoPath, vendorTree,
} from "./lib/oss.mjs";

const CHECK = process.argv.includes("--check");
export const GENERATED_MARK = "{/* Generated by scripts/sync-oss.mjs";
const IMAGE_DIR = "images/oss";
const FACTS_FILE = "snippets/oss-facts.jsx";

const lock = assertVendor();
const map = readMap();
const index = pageIndex(map);
const facts = readFacts();

/** path (repo-relative) → content, for everything this run produces. */
const outputs = new Map();
/** repository paths of every image a page references. */
const images = new Set();
/** links whose target does not exist at the pinned commit. */
const missing = [];

// ── URLs ─────────────────────────────────────────────────────────────────────

const DOCS_ORIGIN = /^https?:\/\/docs\.mirobody\.ai(?=\/|$)/;
const GITHUB_FILE = /^https:\/\/github\.com\/thetahealth\/mirobody\/(?:blob|tree)\/[^/]+\/([^#?]*)(#.*)?$/;

function sitePath(slug, locale, hash = "") {
  return `/${locale}/${slug}${hash}`;
}

/**
 * The ids a link can land on in a repository document: its headings' ids, exactly
 * as render() assigns them, and each `<a id="…">` it writes. A Chinese edition
 * carries its English edition's ids that way (walkthrough's #the-four-promises),
 * since its headings slug to other ids; render() passes the element through.
 */
const idCache = new Map();
function headingIds(repoPath) {
  if (!idCache.has(repoPath)) {
    const tree = unified().use(remarkParse).use(remarkGfm).parse(readVendor(repoPath));
    const h1 = tree.children.findIndex((n) => n.type === "heading" && n.depth === 1);
    if (h1 >= 0) tree.children.splice(h1, 1);
    const slugger = new GithubSlugger();
    const ids = new Set();
    visit(tree, "heading", (node) => ids.add(slugger.slug(toString(node))));
    visit(tree, "html", (node) => {
      for (const m of node.value.matchAll(/<a\s+id="([^"]+)"/g)) ids.add(m[1]);
    });
    idCache.set(repoPath, ids);
  }
  return idCache.get(repoPath);
}

/** anchor fixes applied, and anchors that match no heading or anchor — both reported for upstream. */
const repairedAnchors = [];
const brokenAnchors = [];

/**
 * An `#anchor` must name a heading of the page it points at. A table of contents
 * written against "## 1. Prerequisites" as `#prerequisites` is broken on GitHub too;
 * when exactly one heading matches once its leading number is dropped, point at it.
 */
function checkAnchor(hash, targetRepoPath, ctx) {
  if (!hash || hash === "#" || !targetRepoPath) return hash;
  const wanted = decodeURIComponent(hash.slice(1));
  const ids = headingIds(targetRepoPath);
  if (ids.has(wanted)) return hash;
  const candidates = [...ids].filter((id) => id.replace(/^\d+-/, "") === wanted);
  if (candidates.length === 1) {
    repairedAnchors.push(`${ctx.repoPath}: #${wanted} → #${candidates[0]} (in ${targetRepoPath})`);
    return `#${candidates[0]}`;
  }
  brokenAnchors.push(`${ctx.repoPath}: #${wanted} matches no heading or anchor of ${targetRepoPath}`);
  return hash;
}

function rewriteHref(url, ctx) {
  if (!url) return url;
  if (url.startsWith("#")) return checkAnchor(url, ctx.repoPath, ctx);
  if (DOCS_ORIGIN.test(url)) {
    const rest = url.replace(DOCS_ORIGIN, "");
    const [path, hash = ""] = rest.split("#");
    const clean = path.replace(/\/+$/, "") || "/";
    return hash ? `${clean}#${hash}` : clean;
  }
  const gh = GITHUB_FILE.exec(url);
  if (gh) return repoLink(decodeURIComponent(gh[1]).replace(/\/+$/, ""), gh[2] ?? "", ctx);
  if (/^[a-z][a-z0-9+.-]*:/i.test(url)) return url;
  const [pathPart, hashPart] = url.split("#");
  const hash = hashPart === undefined ? "" : `#${hashPart}`;
  const target = url.startsWith("/")
    ? pathPart.replace(/^\/+/, "")
    : resolveRepoPath(ctx.repoPath, pathPart.split("?")[0]);
  return repoLink(target.replace(/\/+$/, ""), hash, ctx);
}

function repoLink(target, hash, ctx) {
  const page = index.get(target);
  if (page) {
    const locale = page.locale ?? ctx.locale;
    const entry = map.pages.find((p) => p.slug === page.slug);
    // A hand-written translation keeps the English page's heading ids.
    const targetFile = locale === "zh" && entry.zhSource ? entry.zhSource : entry.source;
    return sitePath(page.slug, locale, checkAnchor(hash, targetFile, ctx));
  }
  const tree = vendorTree();
  if (target && !tree.files.has(target) && !tree.dirs.has(target)) {
    missing.push(`${ctx.repoPath} → ${target}`);
  }
  return githubUrl(target, { lock, anchor: hash });
}

function rewriteSrc(url, ctx) {
  if (!url || /^[a-z][a-z0-9+.-]*:/i.test(url) || url.startsWith("/")) return url;
  const target = resolveRepoPath(ctx.repoPath, url.split(/[?#]/)[0]);
  if (!vendorTree().files.has(target)) {
    missing.push(`${ctx.repoPath} → ${target} (image)`);
    return url;
  }
  images.add(target);
  return `/${IMAGE_DIR}/${target}`;
}

// ── raw HTML → JSX ───────────────────────────────────────────────────────────

const VOID = new Set(["area", "br", "col", "embed", "hr", "img", "input", "source", "track", "wbr"]);
const KNOWN = new Set([
  "a", "abbr", "b", "blockquote", "br", "caption", "code", "dd", "del", "details", "div", "dl", "dt",
  "em", "figcaption", "figure", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "img", "ins", "kbd",
  "li", "mark", "ol", "p", "picture", "pre", "q", "s", "samp", "small", "source", "span", "strong",
  "sub", "summary", "sup", "table", "tbody", "td", "th", "thead", "tr", "u", "ul", "var",
]);

const escapeText = (s) => s.replace(/[{}<>]/g, (c) => ({ "{": "&#123;", "}": "&#125;", "<": "&lt;", ">": "&gt;" })[c]);
const escapeAttr = (s) => s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/[{}]/g, (c) => (c === "{" ? "&#123;" : "&#125;"));

function jsxAttributes(properties, ctx) {
  let out = "";
  for (const [key, raw] of Object.entries(properties ?? {})) {
    if (raw === null || raw === undefined || raw === false) continue;
    const info = find(htmlSchema, key);
    const name = /^(data|aria)[A-Z]/.test(key) ? info.attribute : key;
    if (raw === true) {
      out += ` ${name}`;
      continue;
    }
    let value = Array.isArray(raw) ? raw.join(info.commaSeparated ? ", " : " ") : String(raw);
    if (key === "src") value = rewriteSrc(value, ctx);
    if (key === "srcSet") value = value.split(/\s*,\s*/).map((part) => {
      const [src, ...rest] = part.split(/\s+/);
      return [rewriteSrc(src, ctx), ...rest].join(" ");
    }).join(", ");
    if (key === "href") value = rewriteHref(value, ctx);
    if (key === "style") {
      const pairs = value.split(";").map((d) => d.split(":").map((x) => x.trim())).filter(([k, v]) => k && v);
      const obj = pairs.map(([k, v]) => `${JSON.stringify(k.replace(/-([a-z])/g, (_, c) => c.toUpperCase()))}: ${JSON.stringify(v)}`);
      out += ` style={{${obj.join(", ")}}}`;
      continue;
    }
    out += ` ${name}="${escapeAttr(value)}"`;
  }
  return out;
}

/**
 * `<picture>` with light/dark `<source>`s → the light/dark `<img>` pair Mintlify styles.
 * A `(max-width: …)` source is a phone layout: it becomes a second pair shown below
 * Tailwind's `sm` breakpoint (640px), and never stands in for the wide image.
 */
function expandPicture(node) {
  const img = node.children.find((c) => c.type === "element" && c.tagName === "img");
  const sources = node.children.filter((c) => c.type === "element" && c.tagName === "source");
  const media = (s) => String(s.properties.media ?? "");
  const narrow = sources.filter((s) => media(s).includes("max-width"));
  const wide = sources.filter((s) => !narrow.includes(s));
  const isDark = (s) => media(s).includes("prefers-color-scheme: dark");
  const srcOf = (s) => (s ? [].concat(s.properties.srcSet)[0].split(/\s+/)[0] : undefined);
  const light = srcOf(wide.find((s) => media(s).includes("prefers-color-scheme: light"))) ?? img?.properties.src;
  const dark = srcOf(wide.find(isDark));
  const base = { ...(img?.properties ?? {}) };
  delete base.src;
  const image = (src, className) => ({ type: "element", tagName: "img", properties: { ...base, src, className }, children: [] });
  if (!narrow.length) {
    if (!dark) return [image(light)];
    return [image(light, ["block", "dark:hidden"]), image(dark, ["hidden", "dark:block"])];
  }
  const phoneLight = srcOf(narrow.find((s) => !isDark(s)));
  const phoneDark = srcOf(narrow.find(isDark)) ?? phoneLight;
  return [
    image(light, ["hidden", "sm:block", "dark:hidden"]),
    image(dark ?? light, ["hidden", "sm:dark:block"]),
    image(phoneLight, ["block", "sm:hidden", "dark:hidden"]),
    image(phoneDark, ["hidden", "dark:block", "sm:dark:hidden"]),
  ];
}

function hastToJsx(node, ctx) {
  switch (node.type) {
    case "root":
      return node.children.map((c) => hastToJsx(c, ctx)).join("");
    case "text":
      return /^\s+$/.test(node.value) ? (node.value.includes("\n") ? "\n" : " ") : escapeText(node.value);
    case "comment":
    case "doctype":
      return "";
    case "element": {
      if (node.tagName === "picture") return expandPicture(node).map((c) => hastToJsx(c, ctx)).join("\n");
      if (!KNOWN.has(node.tagName)) ctx.warnings.push(`unknown HTML element <${node.tagName}> in ${ctx.repoPath}`);
      const attrs = jsxAttributes(node.properties, ctx);
      if (VOID.has(node.tagName)) return `<${node.tagName}${attrs} />`;
      const inner = node.children.map((c) => hastToJsx(c, ctx)).join("");
      return `<${node.tagName}${attrs}>${inner}</${node.tagName}>`;
    }
    default:
      return "";
  }
}

const TAG = /^<(\/?)([A-Za-z][A-Za-z0-9-]*)\b([^>]*?)(\/?)>$/s;

/**
 * Inline HTML arrives one tag per node (`<sub>`, text, `</sub>`), so it cannot be
 * parsed as a fragment. A tag this site does not know is really text (`<PROVIDER>`
 * in prose); a known one is kept, with void elements self-closed and attributes
 * renamed and rewritten.
 */
function inlineHtml(value, ctx) {
  const trimmed = value.trim();
  if (/^<!--[\s\S]*-->$/.test(trimmed)) return { remove: true };
  const tag = TAG.exec(trimmed);
  if (!tag || !KNOWN.has(tag[2].toLowerCase())) return { text: value };
  const [, closing, name] = tag;
  if (closing) return { html: `</${name.toLowerCase()}>` };
  const tree = fromHtml(trimmed, { fragment: true });
  const element = tree.children.find((c) => c.type === "element");
  if (!element) return { text: value };
  const attrs = jsxAttributes(element.properties, ctx);
  return { html: VOID.has(element.tagName) ? `<${element.tagName}${attrs} />` : `<${element.tagName}${attrs}>` };
}

// ── one page ─────────────────────────────────────────────────────────────────

const INLINE_PARENTS = new Set(["paragraph", "heading", "tableCell", "emphasis", "strong", "delete", "link", "linkReference"]);
const idToken = (id) => `MBHID${Buffer.from(id).toString("hex")}MBHID`;

function yamlString(s) {
  return JSON.stringify(s);
}

function isLanguageSwitcher(node, counterparts) {
  if (node.type !== "paragraph") return false;
  const text = toString(node).trim();
  if (text.length > 24) return false;
  let links = 0;
  let toCounterpart = 0;
  visit(node, "link", (link) => {
    links += 1;
    if (counterparts.some((c) => link.url.split("#")[0].endsWith(c.split("/").pop()))) toCounterpart += 1;
  });
  return links > 0 && links === toCounterpart;
}

async function render(page, locale, { repoPath, fallback = false }) {
  const ctx = { repoPath, locale, warnings: [] };
  const tree = unified().use(remarkParse).use(remarkGfm).parse(readVendor(repoPath));

  const h1 = tree.children.findIndex((n) => n.type === "heading" && n.depth === 1);
  const headingTitle = h1 >= 0 ? toString(tree.children[h1]).trim() : page.slug;
  if (h1 >= 0) tree.children.splice(h1, 1);
  const title = (locale === "zh" && page.zhSource ? headingTitle : page.title ?? headingTitle)
    .replace(/^\p{Extended_Pictographic}\uFE0F?\s*/u, "");

  const counterparts = [page.source, page.zhSource].filter(Boolean).filter((p) => p !== repoPath);
  tree.children = tree.children.filter((node, i) => !(i < 3 && isLanguageSwitcher(node, counterparts)));

  const slugger = new GithubSlugger();
  visit(tree, (node, i, parent) => {
    if (node.type === "heading") {
      node.children.push({ type: "text", value: ` ${idToken(slugger.slug(toString(node)))}` });
      return;
    }
    if (node.type === "link" || node.type === "definition") node.url = rewriteHref(node.url, ctx);
    if (node.type === "image") node.url = rewriteSrc(node.url, ctx);
    if (node.type === "html") {
      if (INLINE_PARENTS.has(parent?.type)) {
        const result = inlineHtml(node.value, ctx);
        if (result.remove) {
          parent.children.splice(i, 1);
          return [SKIP, i];
        }
        if (result.text !== undefined) {
          parent.children[i] = { type: "text", value: result.text };
          return SKIP;
        }
        node.value = result.html;
        return;
      }
      const jsx = hastToJsx(fromHtml(node.value, { fragment: true }), ctx).trim();
      if (!jsx) {
        parent.children.splice(i, 1);
        return [SKIP, i];
      }
      node.value = jsx;
    }
  });

  let body = unified()
    .use(remarkGfm)
    .use(remarkMdx)
    .use(remarkStringify, { bullet: "-", fences: true, rule: "-", listItemIndent: "one", emphasis: "*" })
    .stringify(tree);
  body = body.replace(/MBHID([0-9a-f]+)MBHID/g, (_, hex) => `{#${Buffer.from(hex, "hex").toString()}}`);
  for (const entry of page.jumpTo ?? []) {
    if (!body.includes(`{#${entry.anchor}}`)) {
      throw new Error(`${page.slug}: jumpTo target #${entry.anchor} is absent from ${repoPath}`);
    }
  }

  const description = page.description?.[locale] ?? page.description?.en;
  const label = page.label?.[locale] ?? page.label?.en;
  if (fallback && !page.zhIntro) throw new Error(`${page.slug}: missing zhIntro for the Chinese fallback`);
  const sidebarLabel = fallback ? `${label}（英文）` : label;
  const front = [
    "---",
    `title: ${yamlString(title)}`,
    sidebarLabel && sidebarLabel !== title ? `sidebarTitle: ${yamlString(sidebarLabel)}` : null,
    description ? `description: ${yamlString(description)}` : null,
    "---",
  ].filter(Boolean);
  const header = [
    'import { OssSource } from "/snippets/oss-facts.jsx";',
    "",
    `${GENERATED_MARK} from ${repoPath} in thetahealth/mirobody at ${lock.version} (${lock.commit.slice(0, 7)}). Edit that file upstream: this copy is overwritten on every sync. */}`,
    "",
    `<OssSource path="${repoPath}" lang="${locale}" />`,
    "",
  ];
  if (fallback) header.push(
    "<Note>本页暂无完整中文版。以下先提供中文导读，随后是英文原文。</Note>",
    "",
    `**中文导读：** ${page.zhIntro}`,
    "",
  );
  if (page.jumpTo) header.push(
    locale === "zh" ? "**按任务跳转**" : "**Jump by task**",
    "",
    ...page.jumpTo.map((entry) => `- [${entry[locale]}](#${entry.anchor})`),
    "",
  );

  const text = `${front.join("\n")}\n\n${header.join("\n")}\n${body.trim()}\n`;
  await validate(text, `${locale}/${page.slug}.mdx`);
  for (const w of ctx.warnings) console.warn(`  ! ${w}`);
  return text;
}

/** Compile the page as plain MDX (minus Mintlify's `{#id}` heading suffix) so a syntax error fails here, not in Mintlify's build. */
async function validate(text, file) {
  const plain = text.replace(/ \{#[^}\n]+\}$/gm, "");
  try {
    await compile(plain, { remarkPlugins: [remarkGfm] });
  } catch (error) {
    throw new Error(`${file}: generated MDX does not compile — ${error.message}`);
  }
}

// ── the facts snippet ───────────────────────────────────────────────────────

function factsSnippet() {
  // Mintlify pulls only the exports a page imports into that page, so a component
  // cannot see a sibling export: each one carries its own copy of the data.
  const data = JSON.stringify(facts);
  return `// Generated by scripts/sync-oss.mjs from thetahealth/mirobody ${lock.version} (${lock.commit}).
// Do not edit: run \`npm run oss:sync\`. Mintlify snippets cannot import one another
// and a page receives only the exports it imports, so every export below is
// self-contained and carries the facts it reads.

export const facts = ${JSON.stringify(facts, null, 2)};

export const Fact = ({ k, code = false, sep = ", " }) => {
  const facts = ${data};
  const value = k.split(".").reduce((o, p) => (o == null ? undefined : o[p]), facts);
  if (value === undefined) return <span>{"[unknown fact " + k + "]"}</span>;
  const items = Array.isArray(value) ? value : [value];
  return (
    <>
      {items.map((item, i) => (
        <span key={i}>
          {i > 0 ? sep : null}
          {code ? <code>{String(item)}</code> : String(item)}
        </span>
      ))}
    </>
  );
};

export const ossUrl = (path = "") => {
  const base = "${lock.repo}";
  const commit = "${lock.commit}";
  if (!path) return base + "/tree/" + commit;
  return base + (path.endsWith("/") ? "/tree/" : "/blob/") + commit + "/" + path.replace(/\\/$/, "");
};

export const OssLink = ({ path = "", children }) => {
  const base = "${lock.repo}";
  const commit = "${lock.commit}";
  const href = !path ? base + "/tree/" + commit : base + (path.endsWith("/") ? "/tree/" : "/blob/") + commit + "/" + path.replace(/\\/$/, "");
  return <a href={href}>{children ?? <code>{path}</code>}</a>;
};

export const OssSource = ({ path, lang = "en" }) => {
  const href = "${lock.repo}/blob/${lock.commit}/" + path;
  return (
    <p className="text-sm text-gray-500 dark:text-gray-400">
      {lang === "zh" ? "对应 mirobody " : "For mirobody "}
      <code>${lock.version}</code>
      {lang === "zh" ? " · 源文件 " : " · source "}
      <a href={href}>
        <code>{path}</code>
      </a>
    </p>
  );
};

export const OssVersion = ({ lang = "en" }) => (
  <p className="text-sm text-gray-500 dark:text-gray-400">
    {lang === "zh" ? "对应 mirobody " : "Written for mirobody "}
    <a href="${lock.repo}/tree/${lock.commit}">
      <code>${lock.version}</code>
    </a>
  </p>
);

export const Stages = ({ lang = "en" }) => {
  const readme = ${JSON.stringify(facts.readme)};
  const stages = (readme[lang] || readme.en).stages;
  const inline = (text) =>
    text.split("\`").map((part, i) => (i % 2 ? <code key={i}>{part}</code> : <span key={i}>{part}</span>));
  return (
    <div className="grid gap-4 sm:grid-cols-3 not-prose">
      {stages.map((stage) => (
        <div key={stage.mark} className="rounded-2xl border border-gray-200 dark:border-white/10 p-5">
          <p className="font-semibold text-gray-900 dark:text-gray-100">
            {stage.mark} {stage.name}
          </p>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">{inline(stage.what)}</p>
        </div>
      ))}
    </div>
  );
};
`;
}

// ── run ──────────────────────────────────────────────────────────────────────

for (const page of map.pages) {
  outputs.set(`en/${page.slug}.mdx`, await render(page, "en", { repoPath: page.source }));
  if (page.zhSource) {
    outputs.set(`zh/${page.slug}.mdx`, await render(page, "zh", { repoPath: page.zhSource }));
  } else if (page.zh !== "translation") {
    outputs.set(`zh/${page.slug}.mdx`, await render(page, "zh", { repoPath: page.source, fallback: true }));
  }
}
outputs.set(FACTS_FILE, factsSnippet());

/** Generated pages already on disk, so a page dropped from oss-map.json is removed too. */
function generatedOnDisk() {
  const found = [];
  for (const locale of LOCALES) {
    const dir = join(ROOT, locale);
    for (const file of readdirSync(dir, { recursive: true })) {
      const rel = `${locale}/${String(file).split("\\").join("/")}`;
      if (!rel.endsWith(".mdx")) continue;
      if (readFileSync(join(ROOT, rel), "utf8").includes(GENERATED_MARK)) found.push(rel);
    }
  }
  return found;
}

function filesUnder(dir) {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return [];
  return readdirSync(abs, { recursive: true })
    .map((f) => join(dir, String(f)).split("\\").join("/"))
    .filter((f) => statSync(join(ROOT, f)).isFile());
}

const expectedImages = new Map([...images].sort().map((p) => [`${IMAGE_DIR}/${p}`, join(VENDOR, p)]));
const stale = generatedOnDisk().filter((f) => !outputs.has(f));

if (missing.length) {
  console.log("links to paths that do not exist at the pinned commit (fix upstream):");
  for (const m of [...new Set(missing)]) console.log(`  ! ${m}`);
}
if (repairedAnchors.length) {
  console.log("anchors repaired to the heading they meant (fix upstream):");
  for (const m of [...new Set(repairedAnchors)]) console.log(`  ~ ${m}`);
}
if (brokenAnchors.length) {
  console.log("anchors that match no heading or anchor (fix upstream):");
  for (const m of [...new Set(brokenAnchors)]) console.log(`  ! ${m}`);
}

if (CHECK) {
  const problems = [];
  for (const [file, text] of outputs) {
    const abs = join(ROOT, file);
    if (!existsSync(abs)) problems.push(`${file}: missing — run npm run oss:sync`);
    else if (readFileSync(abs, "utf8") !== text) problems.push(`${file}: differs from what ${lock.version} (${lock.commit.slice(0, 7)}) renders — edit it upstream, then run npm run oss:sync`);
  }
  for (const file of stale) problems.push(`${file}: generated page no longer in oss-map.json`);
  const onDisk = new Set(filesUnder(IMAGE_DIR));
  for (const [file, src] of expectedImages) {
    if (!onDisk.has(file)) problems.push(`${file}: missing image`);
    else if (!readFileSync(join(ROOT, file)).equals(readFileSync(src))) problems.push(`${file}: image differs from the pinned commit`);
    onDisk.delete(file);
  }
  for (const file of onDisk) problems.push(`${file}: image no page references`);
  console.log(`sync check: ${outputs.size - 1} generated pages · ${expectedImages.size} images · facts at ${lock.version}`);
  if (problems.length) {
    for (const p of problems) console.log(`  ✗ ${p}`);
    console.log(`${problems.length} problem(s)`);
    process.exit(1);
  }
  console.log("✓ clean");
} else {
  for (const [file, text] of outputs) {
    mkdirSync(dirname(join(ROOT, file)), { recursive: true });
    writeFileSync(join(ROOT, file), text);
  }
  for (const file of stale) rmSync(join(ROOT, file));
  rmSync(join(ROOT, IMAGE_DIR), { recursive: true, force: true });
  for (const [file, src] of expectedImages) {
    mkdirSync(dirname(join(ROOT, file)), { recursive: true });
    copyFileSync(src, join(ROOT, file));
  }
  console.log(
    `synced mirobody ${lock.version} (${lock.commit.slice(0, 7)}): ${outputs.size - 1} pages · ${expectedImages.size} images · ${FACTS_FILE}` +
      (stale.length ? ` · removed ${stale.map((f) => relative(ROOT, join(ROOT, f))).join(", ")}` : ""),
  );
}
